# -*- encoding: utf-8 -*-
#
# Copyright 2016 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

---
- name: Import grafana repository GPG keys
  rpm_key: state=present key={{ item }}
  with_items:
    - https://packagecloud.io/gpg.key
    - https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana

- name: Install grafana repository
  copy: src=grafana.repo dest=/etc/yum.repos.d/grafana.repo

- name: Install grafana
  yum: name=grafana state=present

- name: Configure grafana server section
  ini_file: dest=/etc/grafana/grafana.ini
            section=server
            option={{ item.option }}
            value={{ item.value }}
            backup=yes
  with_items:
    - { option: 'protocol', value: '{{ grafana_server_protocol }}' }
    - { option: 'http_addr', value: '{{ grafana_server_http_addr }}' }
    - { option: 'http_port', value: '{{ grafana_server_http_port }}' }
  notify: restart grafana-server

- name: Configure grafana security section
  ini_file: dest=/etc/grafana/grafana.ini
            section=security
            option={{ item.option }}
            value={{ item.value }}
            backup=yes
  with_items:
    - { option: 'admin_user', value: '{{ grafana_security_admin_user }}' }
    - { option: 'admin_password', value: '{{ grafana_security_admin_password }}' }
  notify: restart grafana-server


- name: Start grafana-server service
  service: name=grafana-server state=started enabled=yes
