# -*- encoding: utf-8 -*-
#
# Copyright 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

---
- name: Ensure GPG key is correctly installed
  rpm_key: state=present key=https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Ensure elasticsearch yum repo are installed
  copy: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo

- name: Ensure java is installed
  yum: name=java-1.8.0-openjdk state=present

- name: Ensure elasticsearch is installed
  yum: name=elasticsearch state=present

- name: Ensure Elasticsearch listen to all addresses
  lineinfile: dest=/etc/elasticsearch/elasticsearch.yml
              regexp="^network.host{{':'}} 0.0.0.0"
              insertafter="^# network.host:"
              line="network.host{{':'}} 0.0.0.0"

- name: Ensure elasticsearch is started
  service: name=elasticsearch state=started enabled=yes
