---
- name: Make sure we're authenticated on the registry
  containers.podman.podman_login:
    username: "{{ item.value.username }}"
    password: "{{ item.value.password }}"
    registry: "{{ item.key }}"
  no_log: true
  loop: "{{ simple_registry_credentials | ansible.builtin.dict2items }}"
  loop_control:
    label: "{{ item.key }}"
...
